xenit-eu/contentgrid-spring

contentgrid-spring-boot-platform/build.gradle, contentgrid-spring-boot-starter/build.gradle
Before this, consumers needed to explicitly depend on contentgrid-spring-boot-actuators as well. Now they can just depend on the starter again.
=> Fix transitive dependency on actuators

contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/test/fixture/invoicing/InvoicingApplicationTests.java, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/InvoicingApplication.java
This PR allows to reuse the text-fixtures in the thunx integration tests
=> Move ContentGridSpringDataRestConfiguration import from test-fixtures to test

contentgrid-spring-integration-events/src/main/java/com/contentgrid/spring/integration/events/ContentGridPublisherEventListener.java, integration-tests/integration-tests-spring/src/main/java/com/contentgrid/userapps/holmes/dcm/model/Case.java, integration-tests/integration-tests-spring/src/main/java/com/contentgrid/userapps/holmes/dcm/model/Evidence.java, integration-tests/integration-tests-spring/src/main/java/com/contentgrid/userapps/holmes/dcm/repository/EvidenceRepository.java, integration-tests/integration-tests-spring/src/main/resources/application.yml, integration-tests/integration-tests-spring/src/test/java/com/contentgrid/userapps/holmes/dcm/repository/DcmApiRepositoryIntegrationEventsTests.java
Unfortunately, these events say very little and do not contain a
meaningful before/after or diff. There appears to be no way for us to
get this data without reading out the entire join table and the one from
the snapshot, and diffing on that. This is a very expensive operation in
case of a large table.
=> Events for collections [ACC-536]

contentgrid-spring-boot-autoconfigure/src/main/java/com/contentgrid/spring/boot/autoconfigure/data/web/ContentGridSpringDataRestAutoConfiguration.java, contentgrid-spring-boot-autoconfigure/src/main/resources/META-INF/spring.factories, contentgrid-spring-data-rest/src/main/java/org/springframework/data/rest/webmvc/ContentGridRestProperties.java, contentgrid-spring-data-rest/src/main/java/org/springframework/data/rest/webmvc/ContentGridSpringDataRestConfiguration.java, contentgrid-spring-data-rest/src/main/java/org/springframework/data/rest/webmvc/DelegatingRepositoryPropertyReferenceController.java
This is necessary to bridge the gap while bi-directional relations are not yet fully supported.
It default to disabled, because it also has security implications when used in conjunction with thunx
=> Fall back to spring-data-rest implementation for non-implemented cases in DelegatingRepositoryPropertyReferenceController

contentgrid-spring-boot-autoconfigure/src/main/java/com/contentgrid/spring/boot/autoconfigure/data/web/ContentGridSpringDataRestAutoConfiguration.java, contentgrid-spring-boot-starter/build.gradle, contentgrid-spring-data-rest/build.gradle, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/affordances/AffordanceCollectionRepresentationModelProcessor.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/affordances/AffordanceInjectingSelfLinkProvider.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/affordances/ContentGridSpringDataRestAffordancesConfiguration.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/mapping/ContentGridDomainTypeMappingConfiguration.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/mapping/collectionfilter/CollectionFilterBasedContainer.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/mapping/collectionfilter/CollectionFilterBasedProperty.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/webmvc/ContentGridSpringDataRestProfileConfiguration.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/affordances/AffordanceInjectingSelfLinkProviderTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/webmvc/DefaultDomainTypeToHalFormsPayloadMetadataConverterTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/webmvc/HalFormsProfileControllerTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/test/fixture/invoicing/InvoicingApplicationTests.java, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/InvoicingApplication.java, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/model/Customer.java, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/model/Invoice.java, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/model/Order.java, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/model/PromotionCampaign.java, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/model/ShippingAddress.java, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/model/support/Content.java, contentgrid-spring-data-rest/src/testFixtures/resources/application.yml, contentgrid-spring-querydsl/src/main/java/com/contentgrid/spring/querydsl/annotation/CollectionFilterParam.java, contentgrid-spring-querydsl/src/main/java/com/contentgrid/spring/querydsl/annotation/CollectionFilterParams.java, contentgrid-spring-querydsl/src/main/java/com/contentgrid/spring/querydsl/annotation/QuerydslPredicateFactory.java, contentgrid-spring-querydsl/src/main/java/com/contentgrid/spring/querydsl/predicate/Default.java, contentgrid-spring-querydsl/src/main/java/com/contentgrid/spring/querydsl/predicate/None.java
- Make the InvoicingApplication fixture import the full contentgrid starter
- Move contentgrid mapping setup to its own configuration
- Add hal-forms templates to entities
=> Add hal-forms templates to individual entity instances

contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/webmvc/HalFormsProfileController.java
1. We shouldn't be using non-threadsafe RandomGenerators across multiple threads
2. Using the same random across multiple threads can result in lock contention
3. RandomGenerator.getDefault() references a random implementation that is currently not available in all JREs
=> Use old-fashioned Random

contentgrid-spring-boot-autoconfigure/src/main/java/com/contentgrid/spring/boot/autoconfigure/data/web/ContentGridSpringDataRestAutoConfiguration.java, contentgrid-spring-boot-autoconfigure/src/test/java/com/contentgrid/spring/boot/autoconfigure/data/web/ContentGridSpringDataRestAutoConfigurationTest.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/hal/ContentGridCurieConfiguration.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/hal/ContentGridCurieProvider.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/hal/ContentGridSpringDataRestHalConfiguration.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/hal/CurieProviderBuilder.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/hal/CurieProviderCustomizer.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/affordances/AffordanceInjectingSelfLinkProviderTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/hal/ContentGridCurieConfigurationTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/hal/ContentGridCurieProviderTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/hal/ContentGridSpringDataRestHalConfigurationTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/test/fixture/invoicing/InvoicingApplicationTests.java, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/InvoicingApplication.java, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/model/Customer.java, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/model/Invoice.java, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/model/Order.java, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/model/PromotionCampaign.java, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/model/ShippingAddress.java, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/repository/CustomerRepository.java, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/repository/InvoiceRepository.java, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/repository/OrderRepository.java, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/repository/PromotionCampaignRepository.java, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/repository/ShippingAddressRepository.java, contentgrid-spring-integration-events/src/test/java/com/contentgrid/spring/integration/events/ContentGridHalAssemblerTest.java
- Add custom curie provider that does not automatically curie links
- Add utility-methods to CurieProviderCustomizer to register a curie
- Make CurieProvider validate registered curie prefixes and link relations
- Add javadoc to CurieProvider{Builder,Customizer} interfaces
=> Add custom CurieProvider

contentgrid-spring-boot-autoconfigure/build.gradle, contentgrid-spring-boot-autoconfigure/src/main/java/com/contentgrid/spring/boot/autoconfigure/data/web/ContentGridSpringDataRestAutoConfiguration.java, contentgrid-spring-boot-autoconfigure/src/test/java/com/contentgrid/spring/boot/autoconfigure/data/web/ContentGridSpringDataRestAutoConfigurationTest.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/links/AggregateLinkCollector.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/links/ContentGridLinkCollector.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/links/ContentGridLinkRelations.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/links/ContentGridSpringContentRestLinksConfiguration.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/links/ContentGridSpringDataLinksConfiguration.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/links/SpringContentLinkCollector.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/links/SpringDataAssociationLinkCollector.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/links/SpringDataProfileLinksResourceProcessor.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/links/SpringDataRepositoryLinksResourceProcessor.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/webmvc/ProfileLinksResource.java, contentgrid-spring-data-rest/src/main/java/org/springframework/data/rest/webmvc/ContentGridSpringDataRestConfiguration.java, contentgrid-spring-data-rest/src/main/java/org/springframework/data/rest/webmvc/DelegatingProfileController.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/hal/ContentGridCurieConfigurationTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/links/SpringContentLinkCollectorTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/links/SpringDataAssociationLinkCollectorTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/links/SpringDataProfileLinksResourceProcessorTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/links/SpringDataRepositoryLinksResourceProcessorTest.java, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/store/CustomerContentStore.java
These generic link relations: `cg:entity`, `cg:relation` & `cg:content` can be used to build generic integrations that are independent of the datamodel of the application.
Such a generic application can now easily read all content properties from an entity without relying on heuristics to determine which link-relations on an entity object are content and which ones are other relations.
Similarly, a generic application can now discover all available entity types from `/` (or their profiles from `/profile`) by using the `cg:entity` relation, instead of reading all relations and assuming which ones are entities based on heuristics.
Since the generic link relations rely on CURIEs so they are namespaced, they are only activated when a `CurieProviderCustomizer` is defined (and thus when all …
=> Add support for generic link relations based on datamodel

contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/links/ContentGridSpringDataLinksConfiguration.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/links/SpringDataEmbeddedItemResourceProcessor.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/affordances/AffordanceInjectingSelfLinkProviderTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/links/SpringDataProfileLinksResourceProcessorTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/links/SpringDataRepositoryLinksResourceProcessorTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/test/fixture/invoicing/InvoicingApplicationTests.java, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/model/Refund.java, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/repository/RefundRepository.java
- Use 'item' as link-relation for collection resources
- Add 'Refund' model to fixture application
- Ensure that links are present on the copied model
=> Use 'item' link-rel for collection `_embedded` items

contentgrid-spring-boot-autoconfigure/build.gradle, contentgrid-spring-boot-autoconfigure/src/main/java/com/contentgrid/spring/boot/autoconfigure/flyway/FlywayPostgresAutoConfiguration.java
There are some changes made in Flyway between the version shipped in Spring Boot 2 & 3
A default was changed in flyway which results in `CREATE INDEX CONCURRENTLY` in a migration deadlocking during startup
The resolution provided in https://github.com/flyway/flyway/issues/3508 is to set a configuration option for transactional lock to false.
=> Configure flyway to disable transactional lock

contentgrid-spring-boot-platform/build.gradle, contentgrid-spring-data-rest/build.gradle, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/querydsl/mapping/CollectionFiltersImpl.java, contentgrid-spring-data-rest/src/main/java/org/springframework/data/rest/webmvc/ContentGridSpringDataRestConfiguration.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/test/fixture/invoicing/InvoicingApplicationTests.java, contentgrid-spring-querydsl/build.gradle, contentgrid-spring-querydsl/src/main/java/com/contentgrid/spring/querydsl/converter/CollectionFilterQuerydslPredicateConverter.java, contentgrid-spring-querydsl/src/main/java/com/contentgrid/spring/querydsl/converter/InvalidCollectionFilterValueException.java, contentgrid-spring-querydsl/src/main/java/com/contentgrid/spring/querydsl/mapping/CollectionFilters.java, contentgrid-spring-querydsl/src/main/java/com/contentgrid/spring/querydsl/resolver/CollectionFilterParamPredicateResolver.java, contentgrid-spring-querydsl/src/test/java/com/contentgrid/spring/querydsl/converter/CollectionFilterQuerydslPredicateConverterTest.java, integration-tests/integration-tests-spring/build.gradle, settings.gradle
Using the CollectionFilter-based filters allow a couple of additional features:
- Only having to define the filters in one place (no more `QuerydslBinderCustomizer` in repositories)
- Support multiple query parameters bound to the same `Path`, with different actions (like being able to do greater than/less than queries)
=> Replace spring data QuerydslBinder with CollectionFilter-based search filters

contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/hal/ContentGridCurieProvider.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/links/ContentGridSpringDataLinksConfiguration.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/links/SpringDataEmbeddedCuriesResourceProcessor.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/test/fixture/invoicing/InvoicingApplicationTests.java
Because the _embedded link-rel itself is no longer a curied link,
spring-data-rest no longer adds the curies link-rel to the top level item;
even though resources inside the embedded collection have link relations
that require curies to be resolved.
Solving this for all collections with EmbeddedWrappers by adding curies
in a ResourceProcessor if hitting the case when spring-data-rest does not add
curies.
=> Ensure that curies are present on the collection resource

contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/links/AggregateLinkCollector.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/test/fixture/invoicing/InvoicingApplicationTests.java, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/model/support/Content.java
Calling the `getLinksFor()` delegate method was not intended, and results in a problem when having `@Embedded` objects, as those have no self link, nor an ID to put in a self link
=> Call correct delegate method in `AggregateLinkCollector#getLinksForNested()`

contentgrid-spring-data-rest/src/main/java/org/springframework/data/rest/webmvc/DelegatingRepositoryPropertyReferenceController.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/querydsl/mapping/CollectionFiltersMappingImplTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/querydsl/paths/PathNavigatorTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/webmvc/DefaultDomainTypeToHalFormsPayloadMetadataConverterTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/webmvc/HalFormsProfileControllerTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/test/fixture/invoicing/InvoicingApplicationTests.java, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/model/Invoice.java, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/model/Order.java
To support permissions on -to-many relations, we have a feature in to automatically redirect to collection of the target of the relation, with a collection filter applied.
For example: `/invoices/$id/orders` becomes `/orders?invoice._id=$id`
To be able to apply a collection filter on the target domain type, that type needs a reference to the source domain type. (so, a bi-directional relation)
We don’t want to implement full user-configurable bi-directional relations for now, since that requires additional considerations.
The complications of bi-directional relations in JPA:
- The inverse side of a relation is read-only: Hibernate does not look at the inverse side of the relation when saving changes
- The `@ManyToOne` relation annotation does not have a `mappedBy` attribute, so in a …
=> Support one-to-many redirect with pseudo-inverse relation using a plain Column

contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/links/SpringDataAssociationLinkCollector.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/affordances/AffordanceInjectingSelfLinkProviderTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/links/SpringDataAssociationLinkCollectorTest.java
- For to-one relations, the hal-forms templates on the entity allow both to set a relation and to clear a relation
- For to-many relations, we can only add a template to add items to a relation, as removing items from a relation must happen on a per-item basis
For now we leave adding a template to remove an item for a to-many relation out of scope.
=> Add HAL-FORMS templates for modifying relations

contentgrid-spring-data-rest/build.gradle, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/InvoicingApplication.java, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/model/Invoice.java, contentgrid-spring-data-rest/src/testFixtures/resources/application.yml, contentgrid-spring-integration-events/src/test/java/com/contentgrid/spring/integration/events/EntityChangeHibernateEventListenerTest.java
It turns out that the jdbc-based testcontainers has a problem where all
connections that use the same jdbc url are shared to the same database
instance. This causes a problem when tests run in parallel, as hibernate
sets up and destroys the schema on every application context start, but
it's all on the same database.
Using the spring `@ServiceConnection` instead ensures that a different
database is started for every time the application context is
(re)created, avoiding any problems with a shared database
=> Fix database isolation in tests

contentgrid-spring-boot-autoconfigure/src/main/java/com/contentgrid/spring/boot/autoconfigure/data/web/ContentGridSpringDataRestAutoConfiguration.java, contentgrid-spring-data-rest/build.gradle, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/mapping/ContentGridDomainTypeMappingConfiguration.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/mapping/DomainTypeMapping.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/mapping/PlainMapping.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/problem/ContentGridExceptionHandler.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/problem/ContentGridProblemDetailsConfiguration.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/problem/JsonPropertyPathConverter.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/problem/ProblemFactory.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/problem/ProblemType.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/problem/ProblemTypeMessageSource.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/problem/ProblemTypeUrlFactory.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/problem/ResponseEntityFactory.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/problem/SpringContentRestExceptionHandler.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/problem/SpringDataRestRepositoryExceptionHandler.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/problem/ext/ConstraintViolationProblemProperties.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/problem/ext/MergedProblemProperties.java, contentgrid-spring-data-rest/src/main/resources/com/contentgrid/spring/data/rest/problem/messages.properties, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/problem/ContentGridProblemDetailsConfigurationIntegrationTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/problem/JsonPropertyPathConverterTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/problem/ProblemDetailsMockMvcMatchers.java
Using [problem details](https://www.rfc-editor.org/rfc/rfc7807) for reporting errors to the client allows for returning a more specific error to the client than HTTP status codes allow.
Clients can use the specific error codes to show a proper message to end-users in the UI, or to autonomously take action to rectify the cause of the error.
=> Use RFC7807 problem details for reporting errors

contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/problem/ContentGridExceptionHandler.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/validation/BeanValidationRepositoryEventListener.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/validation/OnEntityDelete.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/problem/ContentGridProblemDetailsConfigurationIntegrationTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/validation/BeanValidationRepositoryEventListenerTest.java, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/model/Customer.java, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/model/Invoice.java
Normally, this would result in a foreign key constraint violation, resulting in a generic constraint violation problem report. That doesn't help a lot, because it doesn't tell you *which* relation is still referencing your entity.
Using a separate validation group, we can verify that there are no entities referencing our entity anymore (thanks to the inverse relations), and raise a specific validation error in case the entity is still being referenced.
=> Improve problem reporting for entity that is still referenced by required relations when it is deleted

contentgrid-spring-audit-logging/src/main/java/com/contentgrid/spring/audit/AuditObservationHandler.java, contentgrid-spring-audit-logging/src/main/java/com/contentgrid/spring/audit/handler/messaging/MessageSendingAuditHandler.java, contentgrid-spring-audit-logging/src/test/java/com/contentgrid/spring/audit/AuditObservationHandlerTest.java, contentgrid-spring-boot-autoconfigure/src/main/java/com/contentgrid/spring/boot/autoconfigure/audit/ContentGridAuditMessagingAutoConfiguration.java, contentgrid-spring-boot-autoconfigure/src/test/java/com/contentgrid/spring/boot/autoconfigure/audit/ContentGridAuditMessagingAutoConfigurationTest.java
- Ensure that AuditObservationHandler does not throw exceptions
- Disable MessageSendingAuditHandler when no destination is configured
=> Handle exceptions during processing audit messages

integration-tests/integration-tests-spring/src/test/java/com/contentgrid/userapps/holmes/dcm/DcmApiApplicationTestsWithContentGridLinkRels.java
This ensures that the integration tests cover the whole customized links configurations as well
=> Add test for generated contentgrid application with the contentgrid linkrels/curies enabled

.github/workflows/ci.yml, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/links/ContentGridSpringDataLinksConfiguration.java
HAL specifies that links should not switch between a list and a single value.
`cg:entity`, `cg:relation` & `cg:content` are always used in a context where there are potentially multiple entries present.
Because this feature uses the new `MediaTypeConfigurationCustomizer` from spring-hateoas 2.2, **support for Spring Boot 3.1 is dropped.**
=> Make cg:entity, cg:relation & cg:content links always an array

contentgrid-spring-boot-autoconfigure/src/main/java/com/contentgrid/spring/boot/autoconfigure/data/web/ContentGridSpringDataRestAutoConfiguration.java, contentgrid-spring-boot-autoconfigure/src/test/java/com/contentgrid/spring/boot/autoconfigure/data/web/ContentGridSpringDataRestAutoConfigurationTest.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/hal/forms/ContentGridHalFormsConfiguration.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/hal/forms/HalFormsRelationFieldOptionsCustomizer.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/webmvc/ContentGridSpringDataRestProfileConfiguration.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/hal/forms/ContentGridHalFormsConfigurationTest.java
The MediaTypeConfigurationCustomizer is a new way to configure HalFormsConfiguration without creating the whole configuration in one place.
Since we only need to configure hal-forms options on some fields, it is a good candidate to be moved to the MediaTypeConfigurationCustomizer approach.
Also add tests that check that the options are added correctly to relations.
=> Use new MediaTypeConfigurationCustomizer to customize HalFormsConfiguration

contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/etag/OptimisticLockingTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/test/fixture/invoicing/InvoicingApplicationTests.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/test/matchers/ETagHeaderMatcher.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/test/matchers/ExtendedHeaderResultMatchers.java, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/model/Order.java, contentgrid-spring-integration-events/src/test/java/com/contentgrid/spring/integration/events/EntityChangeHibernateEventListenerTest.java
Move optimistic locking tests about `If-Match` and `ETag` headers from `InvoicingApplicationTest` to a new file
=> Move etag header tests to separate test file

contentgrid-spring-data-rest/src/main/java/org/springframework/data/rest/webmvc/DelegatingRepositoryPropertyReferenceController.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/webmvc/DefaultDomainTypeToHalFormsPayloadMetadataConverterTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/test/fixture/invoicing/InvoicingApplicationTests.java, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/model/Order.java, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/model/PromotionCampaign.java
Reproduction steps:
1. Have an entity (order) with multiple many-to-many relations (promos & manual-promos) to the same target entity (promotions)
2. Create an order, try to follow the relations to promotions
3. Notice that both relations redirect to the same URL with the same query filter parameters
In the example here, following the relation to manual-promos redirects to `/promotions?orders=d69ab994-0a7f-4758-9835-5247785fe55d`, which is the inverse relation of `promos`, not `manual-promos`
Also refactored this piece of code to use the spring data
`PersistentEntity` abstraction instead of raw reflection.
=> Fix many-to-many relations to same target entity are mixed-up when following a relation

contentgrid-spring-boot-platform/build.gradle
Without this exception, gradle won't let us publish the enforcedPlatform dependency statement.
> \* What went wrong:
Execution failed for task ':contentgrid-spring-boot-platform:generateMetadataFileForPlatformPublication'.
> Invalid publication 'platform':
- Variant 'apiElements' contains a dependency on enforced platform 'org.springframework.boot:spring-boot-dependencies'
- Variant 'runtimeElements' contains a dependency on enforced platform 'org.springframework.boot:spring-boot-dependencies'
In general publishing dependencies to enforced platforms is a mistake: enforced platforms shouldn't be used for published components because they behave like forced dependencies and leak to consumers. This can result in hard to diagnose dependency resolution errors. If you did this intentionally you …
=> Use strict version instead of enforcedPlatform

contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/auditing/AuditMetadataTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/auditing/ContentLastModifiedTest.java
The rest controller of spring-content uses the file metadata instead of the entity `@LastModifiedBy` metadata for setting the `Last-Modified` header or checking the `If-Unmodified-Since` header. Therefore tests for checking these headers for content endpoints don't belong under `AuditMetadataTest` and are moved to `LastModifiedContentTest`
=> [ACC-1460] add last-modified tests for content properties

contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/hal/forms/ContentGridHalFormsConfiguration.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/hal/forms/HalFormsAttributeFieldOptionsCustomizer.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/validation/AllowedValues.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/validation/AllowedValuesValidator.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/webmvc/DefaultDomainTypeToHalFormsPayloadMetadataConverter.java, contentgrid-spring-data-rest/src/main/resources/ValidationMessages.properties, contentgrid-spring-data-rest/src/main/resources/com/contentgrid/spring/data/rest/validation/ValidationMessages.properties, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/affordances/AffordanceInjectingSelfLinkProviderTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/auditing/AuditMetadataTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/auditing/ContentLastModifiedTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/etag/OptimisticLockingTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/hal/forms/ContentGridHalFormsConfigurationTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/messages/HalLinkTitlesAndFormPromptsTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/problem/ContentGridProblemDetailsConfigurationIntegrationTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/webmvc/DefaultDomainTypeToHalFormsPayloadMetadataConverterTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/webmvc/HalFormsProfileControllerWithMultipartTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/webmvc/HalFormsProfileControllerWithoutMultipartTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/test/fixture/invoicing/InvoicingApplicationTests.java, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/model/Customer.java
String Attributes can now be annotated with `@AllowedValues` to limit the possible values that can be assigned to it. The options are also shown in the Hal-Forms templates
=> Add AllowedValues constraint annotation [ACC-1466]

contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/hal/forms/HalFormsAttributeFieldOptionsCustomizer.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/hal/forms/ContentGridHalFormsConfigurationTest.java
The HAL-FORMS definition that is generated for a list-of-values constraint is:
```json
{
"name" : "gender",
"type" : "text",
"options" : {
"inline" : [ "female", "male" ]
}
}
```
This is valid syntax, but it implies that the field is multi-valued, supporting 0 to infinity items to be selected.
In reality, name is a single-value field, so the correct definition would be
```json
{
"name" : "gender",
"type" : "text",
"options" : {
"inline" : [ "female", "male" ]
"maxItems": 1
}
}
```
This indicates that the field is single-valued, because a maximum of 1 item can be submitted.
`minItems` can optionally also be supplied, set to 0 or 1 to indicate if the field is optional or required. However, this functionality is already covered with a required flag on the property definition, so it's not …
=> Ensure that minItems/maxItems is set on AllowedValues-constrainted properties

contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/hal/forms/ContentGridHalFormsConfiguration.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/hal/forms/HalFormsAttributeFieldOptionsCustomizer.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/querydsl/mapping/CollectionFiltersMappingImplTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/hal/forms/ContentGridHalFormsConfigurationTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/messages/HalLinkTitlesAndFormPromptsTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/webmvc/AbstractHalFormsProfileControllerTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/webmvc/DefaultDomainTypeToHalFormsPayloadMetadataConverterTest.java, contentgrid-spring-data-rest/src/testFixtures/java/com/contentgrid/spring/test/fixture/invoicing/model/Customer.java
For search filters that have a different name than the property itself,
also create the options for AllowedValues, so a select can be shown for
them as well
=> Apply `@AllowedValues` constraint on all search filters

contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/querydsl/mapping/AbstractCollectionFiltersImpl.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/querydsl/mapping/CollectionFilterImpl.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/querydsl/mapping/PredicateCollectionFiltersImpl.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/querydsl/sort/CollectionFilterSortHandlerMethodArgumentResolver.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/querydsl/sort/ContentGridCollectionFilterSortConfiguration.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/querydsl/sort/LazyResolvingHandlerMethodArgumentResolver.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/querydsl/sort/PassthroughDefaultedPageableMethodArgumentResolver.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/querydsl/sort/QSortWithOriginalSort.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/querydsl/sort/UnsupportedSortPropertyException.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/problem/ContentGridExceptionHandler.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/problem/ContentGridProblemDetailsConfiguration.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/problem/ProblemType.java, contentgrid-spring-data-rest/src/main/java/org/springframework/data/rest/webmvc/ContentGridSpringDataRestConfiguration.java, contentgrid-spring-data-rest/src/main/resources/com/contentgrid/spring/data/rest/problem/messages.properties, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/querydsl/mapping/CollectionFiltersFactoryTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/querydsl/mapping/CollectionFiltersMappingImplTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/querydsl/sort/CollectionFilterSortHandlerMethodArgumentResolverTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/problem/ContentGridProblemDetailsConfigurationIntegrationTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/test/fixture/invoicing/InvoicingApplicationTests.java, contentgrid-spring-querydsl/src/main/java/com/contentgrid/spring/querydsl/annotation/CollectionFilterParam.java, contentgrid-spring-querydsl/src/main/java/com/contentgrid/spring/querydsl/annotation/QuerydslPredicateFactory.java, contentgrid-spring-querydsl/src/main/java/com/contentgrid/spring/querydsl/mapping/CollectionFilter.java, contentgrid-spring-querydsl/src/main/java/com/contentgrid/spring/querydsl/mapping/CollectionFilters.java, contentgrid-spring-querydsl/src/main/java/com/contentgrid/spring/querydsl/mapping/CollectionFiltersMapping.java, contentgrid-spring-querydsl/src/main/java/com/contentgrid/spring/querydsl/predicate/Default.java, contentgrid-spring-querydsl/src/main/java/com/contentgrid/spring/querydsl/predicate/Text.java, contentgrid-spring-querydsl/src/main/java/com/contentgrid/spring/querydsl/resolver/CollectionFilterParamPredicateResolver.java, contentgrid-spring-querydsl/src/testFixtures/java/com/contentgrid/spring/querydsl/test/mapping/TestCollectionFilter.java
- **First iteration to allow sorting on fields using the CollectionFilterParam name**
- **Move logic to create an `OrderSpecifier` to `QuerydslPredicateFactory`**
- **Add javadoc to CollectionFilter mapping APIs**
=> Implement sorting using `@CollectionFilterParam` infrastructure

contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/querydsl/mapping/CollectionFilterImpl.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/querydsl/mapping/CollectionFiltersFactory.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/hal/forms/HalFormsAttributeFieldOptionsCustomizer.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/webmvc/DefaultDomainTypeToHalFormsPayloadMetadataConverter.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/querydsl/mapping/CollectionFiltersFactoryTest.java, contentgrid-spring-querydsl/src/main/java/com/contentgrid/spring/querydsl/mapping/CollectionFilter.java, contentgrid-spring-querydsl/src/test/java/com/contentgrid/spring/querydsl/converter/CollectionFilterQuerydslPredicateConverterTest.java, contentgrid-spring-querydsl/src/testFixtures/java/com/contentgrid/spring/querydsl/test/mapping/TestCollectionFilter.java
- Add direct reference to AnnotatedElement from CollectionFilter
Previously, this was done via the `Path`; which is not necessarily the annotated item
- Early-error when attempting to bind to multiple paths
This previously already caused an error, but an unclear error about a duplicate filter name. It is now a dedicated error message referring to this situation.
=> Minor refactorings around CollectionFilter APIs

contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/querydsl/sort/CollectionFilterSortHandlerMethodArgumentResolver.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/querydsl/sort/CollectionFilterSortHandlerMethodArgumentResolverTest.java, contentgrid-spring-data-rest/src/testFixtures/resources/application.yml
With standard spring-data-rest, the sort parameter name is configurable using configuration parameter `spring.data.rest.sort-param-name`.
Due to the overridden `SortHandlerMethodArgumentResolver`, this configuration was not applied consistently in all places.
In URI templates on the root and in URI generation, the default parameter name `sort` was always being used.
This PR adds fixes this problem and adds tests to validate that the configured parameter is always used.
=> Fix configurability of sort parameter

contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/problem/ContentGridProblemDetailsConfigurationIntegrationTest.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/test/fixture/invoicing/InvoicingApplicationTests.java
Test constraint violations for entity creates using multipart/form-data too (not only application/json).
Status of `400 Bad Request` is checked in `validationConstraintViolation()`  (See https://github.com/xenit-eu/contentgrid-spring/blob/v0.16.0/contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/problem/ProblemDetailsMockMvcMatchers.java#L98).
=> ACC-1601: add constraint violation tests with multipart/form-data

contentgrid-spring-boot-autoconfigure/src/main/java/com/contentgrid/spring/boot/autoconfigure/data/web/ContentGridSpringDataRestAutoConfiguration.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/hal/forms/ContentGridHalFormsConfigurationTest.java, contentgrid-spring-integration-events/src/test/java/com/contentgrid/spring/integration/events/ChangeEventPublicationIntegrationTest.java
`cg:content` & `cg:relation` links are not an array when there is only a single value.
This happens because spring-data-rest does not process `MediaTypeConfigurationCustomizer`, so it does not apply the configuration when pulling the `HalConfiguration` bean directly.
This leads to the configuration settings in `HalConfiguration` inconsistently being applied, depending on if a setting is used in spring-hateoas or spring-data-rest.
Always applying all customizers directly in a `BeanPostProcessor` ensures that the HalConfiguration bean itself has all the customizations directly baked-in,
and does not require all consumers to be aware of `MediaTypeConfigurationCustomizer`.
This _does_ result in `MediaTypeConfigurationCustomizer`s being applied twice where `HalConfiguration` is used in …
=> Ensure that HalConfiguration MediaTypeConfigurationCustomizers are always run

contentgrid-spring-data-rest/build.gradle, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/links/AggregateLinkCollector.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/links/ContentGridLinkCollector.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/links/ContentGridSpringContentRestLinksConfiguration.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/links/ContentGridSpringDataLinksConfiguration.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/links/LambdaSafe.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/links/SpringContentLinkCollector.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/links/SpringDataAssociationLinkCollector.java
Make it possible to scope a ContentGridLinkCollector to a single entity type with a generic type argument.
The LambdaSafe class allows us to safely call only the collectors that match the entity type
=> Allow scoping ContentGridLinkCollector to specific entities

contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/links/ContentGridSpringContentRestLinksConfiguration.java, contentgrid-spring-data-rest/src/main/java/com/contentgrid/spring/data/rest/links/ContentGridSpringDataLinksConfiguration.java, contentgrid-spring-data-rest/src/test/java/com/contentgrid/spring/data/rest/links/ContentGridSpringDataLinksConfigurationTest.java
Using `ObjectProvider#iterator()` returns beans in an unsorted way.
This causes problems when a user-defined `ContentGridLinkCollector` bean tries to use or modify links that are supposed to be added by the `ContentGridLinkCollector`s defined in this project; as the processing order would not be stable.
Using `ObjectProvider#orderedStream()` instead, beans are properly sorted based on their `@Order`.
To allow user-defined `ContentGridLinkCollector`s to order themselves before or after the system-defined ones, place system-defined ones in a neutral position (instead of the `@Order` default lowest-precedence).
Without supplying any `@Order`, beans will be regarded as lowest-precedence, and they are now automatically ordered after the system-defined `ContentGridLinkCollector`s
=> Order supplied `ContentGridLinkCollector`s to be in a neutral position

contentgrid-spring-common/src/main/java/com/contentgrid/spring/common/ContentGridApplicationPropertiesConfiguration.java, contentgrid-spring-common/src/main/java/com/contentgrid/spring/common/ContentGridExtensionProperties.java
Extension registration is used for supplying extension base URIs that are dependent on the deployment environment.
This way, it can be avoided to hardcode domains for external services, which might change independently of the application itself.
=> Add extension registration properties

contentgrid-spring-data-rest/src/main/java/org/springframework/data/rest/webmvc/DelegatingRepositoryPropertyReferenceController.java, contentgrid-spring-data-rest/src/test/java/org/springframework/data/rest/webmvc/DelegatingRepositoryPropertyReferenceControllerTest.java, contentgrid-spring-data-rest/src/test/java/org/springframework/data/rest/webmvc/SourceEntity1.java, contentgrid-spring-data-rest/src/test/java/org/springframework/data/rest/webmvc/SourceEntity1Repository.java, contentgrid-spring-data-rest/src/test/java/org/springframework/data/rest/webmvc/SourceEntity2.java, contentgrid-spring-data-rest/src/test/java/org/springframework/data/rest/webmvc/SourceEntity2Repository.java, contentgrid-spring-data-rest/src/test/java/org/springframework/data/rest/webmvc/TargetEntity.java, contentgrid-spring-data-rest/src/test/java/org/springframework/data/rest/webmvc/TargetEntityRepository.java
When multiple many-to-many relations with the same name (from different
source entities) target the same entity; the GET relation endpoint did
not redirect with the correct collection filter.
It should be considered that multiple `@ManyToMany(mappedBy="...")`
annotations with the same `mappedBy` value can legally be present when
they refer to different entities on the other side.
=> Prevent clashes between m2m relations with the same name
